apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-internal-cd
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
