apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volkn-kube-cd
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - '*'
